import test from 'node:test';
import assert from 'node:assert/strict';
import { AuditRecorder } from '../../../dist/index.js';
import { gateFixture } from '../gates/fixtures.mjs';
import { hash } from '../risk/fixtures.mjs';
const time='2026-10-04T14:00:00Z';
function fixture() {const f=gateFixture();return {...f,audit:new AuditRecorder({redact:payload=>({...payload, ...(payload.message?{message:'[REDACTED]'}:{})})},{execution_id:'execution',task_id:f.id,profile_hash:hash('profile'),commit_before:'base'},f.runner,'IMPLEMENTATION_GATE')};}
function validating(f){f.audit.transition('CREATED','CONTEXT_READY',time);f.audit.transition('CONTEXT_READY','RUNNING',time);f.audit.transition('RUNNING','VALIDATING',time);}
test('sequence, redaction before hash, immutable export and tamper detection',()=>{const f=fixture();f.audit.append('CONTEXT',{token:'do-not-store',message:'raw-secret'},time);f.audit.append('PROFILE',{reference:'profile-ref'},time);assert.equal(f.audit.events[0].payload.token,'[REDACTED]');assert.equal(f.audit.events[0].payload.message,'[REDACTED]');assert.equal(f.audit.events[1].sequence,2);assert(f.audit.verify());assert(Object.isFrozen(f.audit.events[0].payload));const changed=structuredClone(f.audit.events);changed[0].payload.token='tampered';assert.equal(f.audit.verify(changed),false);changed[0].sequence=2;assert.equal(f.audit.verify(changed),false);});
test('successful lifecycle records reconstructable references and finalizes idempotently',()=>{const f=fixture();for(const kind of ['role_evidence_refs','review_assignment_refs','finding_refs'])f.audit.recordReference(kind,kind+'-ref',time);validating(f);f.audit.recordGateResult(f.runner.runGate('IMPLEMENTATION_GATE',f.id,time));f.audit.transition('VALIDATING','COMPLETED',time);const result=f.audit.finalize(time);assert.equal(result.final_status,'COMPLETED');assert.equal(result.gate_results.length,1);assert.equal(result.finding_refs.length,1);assert.strictEqual(f.audit.finalize(time),result);assert.throws(()=>f.audit.finalize('2026-10-04T14:01:00Z'));assert.throws(()=>f.audit.append('AFTER',{},time));});
test('missing, failed or clarification gate prevents completion',()=>{for(const status of [null,'FAILED','NEEDS_CLARIFICATION']){const f=fixture();validating(f);if(status){f.admission.criteria[0].status=status;f.audit.recordGateResult(f.runner.runGate('IMPLEMENTATION_GATE',f.id,time));}assert.throws(()=>f.audit.transition('VALIDATING','COMPLETED',time));assert.equal(f.audit.state,'VALIDATING');}});
test('changed host review evidence invalidates recorded PASS',()=>{const f=fixture();validating(f);f.audit.recordGateResult(f.runner.runGate('IMPLEMENTATION_GATE',f.id,time));f.admission.reviews.pop();assert.throws(()=>f.audit.transition('VALIDATING','COMPLETED',time));});
test('forged Gate, conflicting Gate and illegal lifecycle reject',()=>{const f=fixture();assert.throws(()=>f.audit.recordGateResult({gate_id:'IMPLEMENTATION_GATE',status:'PASS',evidence:[],timestamp:time,artifact_hashes:[],reviewer:'caller'}));const g=fixture();const a=g.runner.runGate('IMPLEMENTATION_GATE',g.id,time);g.audit.recordGateResult(a);g.audit.recordGateResult(a);g.admission.criteria[0].status='FAILED';assert.throws(()=>g.audit.recordGateResult(g.runner.runGate('IMPLEMENTATION_GATE',g.id,time)));assert.throws(()=>g.audit.transition('CREATED','COMPLETED',time));assert.throws(()=>g.audit.finalize(time));});
test('review records are schema checked and stored as content addressed audit events',()=>{const f=fixture();f.audit.recordEvidence(f.admission.reviews[0],time);validating(f);f.audit.recordGateResult(f.runner.runGate('IMPLEMENTATION_GATE',f.id,time));f.audit.transition('VALIDATING','COMPLETED',time);const final=f.audit.finalize(time);assert.equal(final.role_evidence_refs[0],f.audit.events[0].hash);assert.equal(f.audit.events[0].payload.record.evidence_id,'QA_REVIEWER');});
test('redaction failure terminates unsafe continuation with catalog error',()=>{const f=gateFixture();const audit=new AuditRecorder({redact:()=>{throw new Error('private-host-error')}},{execution_id:'execution',task_id:f.id,profile_hash:hash('profile'),commit_before:'base'},f.runner,'IMPLEMENTATION_GATE');assert.throws(()=>audit.append('EVENT',{},time),e=>e.code==='HNS-AUD-001'&&!e.message.includes('private-host-error'));assert.equal(audit.state,'FAILED_RUNTIME');assert.throws(()=>audit.append('RETRY',{},time));assert.throws(()=>audit.finalize(time));});
test('Gate from another runner cannot be recorded',()=>{const f=fixture();const other=gateFixture();assert.throws(()=>f.audit.recordGateResult(other.runner.runGate('IMPLEMENTATION_GATE',other.id,time)),e=>e.code==='HNS-AUD-001');});
test('current evidence drift after completion prevents finalization',()=>{const f=fixture();validating(f);f.audit.recordGateResult(f.runner.runGate('IMPLEMENTATION_GATE',f.id,time));f.audit.transition('VALIDATING','COMPLETED',time);f.admission.reviews.pop();assert.throws(()=>f.audit.finalize(time));});
