import test from 'node:test';import assert from 'node:assert/strict';import {Workbench,repoURL,text,projectId} from '../public/client.mjs';
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',P='33333333-3333-4333-8333-333333333333',Q='44444444-4444-4444-8444-444444444444';
const response=(data,status=200)=>({ok:status<400,status,json:async()=>data});
function setup(fetcher){const data=new Map(),storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};const app=new Workbench({url:'https://example.supabase.co',key:'public'},{fetcher,storage,now:()=>100});return {app,data};}
function logged(app){app.state.user={id:A};app.state.session={token:'verified-token',expiresAt:10000};app.state.view='project';app.state.project={id:P,owner_id:A,plan:'old',repo_url:''};app.state.draft={plan:'draft',note:'note draft',repo:''};}
test('login uses verified /user identity, not token user claims; persists tab token only',async()=>{const calls=[];const {app,data}=setup(async(url,opts)=>{calls.push([url,opts]);if(url.includes('/token'))return response({access_token:'opaque',expires_in:10,user:{id:B}});if(url.endsWith('/user'))return response({id:A});return response([]);});await app.login('user@example.com','password');assert.equal(app.state.user.id,A);assert.deepEqual(JSON.parse(data.get('wb-session')),{token:'opaque',expiresAt:10100});assert.equal(calls[1][1].headers.Authorization,'Bearer opaque');assert.equal(JSON.stringify([...data]).includes('password'),false);});
test('failed /user authentication never stores a session or reads projects',async()=>{let count=0;const {app,data}=setup(async url=>{count++;return url.includes('/token')?response({access_token:'opaque',expires_in:10}):response({},401);});await app.login('x','y');assert.equal(app.state.user,null);assert.equal(data.size,0);assert.equal(count,2);});
test('late A response after B selection cannot restore A data',async()=>{let release;const blocked=new Promise(r=>release=r);const {app}=setup(async url=>{if(url.includes('id=eq.'+P)){await blocked;return response([{id:P,owner_id:A,plan:'A',repo_url:''}]);}if(url.includes('wb_notes'))return response([]);return response([{id:Q,owner_id:A,plan:'B',repo_url:''}]);});logged(app);const old=app.open(P);await app.open(Q);release();await old;assert.equal(app.state.project.id,Q);assert.equal(app.state.draft.plan,'B');});
test('failed B load clears A and cannot mutate; wrong owner rows rejected',async()=>{let posts=0;const {app}=setup(async(url,opts)=>{if(opts.method!=='GET')posts++;return response([{id:Q,owner_id:B,plan:'foreign'}]);});logged(app);await app.open(Q);assert.equal(app.state.project,null);assert.equal(app.state.draft.plan,'');await app.save('plan');assert.equal(posts,0);assert.match(app.state.error,/無法存取/);});
test('zero-row and network mutation failures retain draft and never auto-retry',async()=>{let calls=0;const {app}=setup(async()=>{calls++;return response([]);});logged(app);await app.save('plan');assert.equal(app.state.draft.plan,'draft');assert.match(app.state.status,/尚未保存/);assert.equal(calls,1);assert.equal(app.state.project.plan,'old');});
test('401 preserves in-memory bound draft and clears tab session; logout drops recovery',async()=>{const {app,data}=setup(async()=>response({},401));logged(app);data.set('wb-session','token');await app.save('note');assert.equal(app.state.user,null);assert.equal(app.state.project,null);assert.equal(app.recovery.user,A);assert.equal(app.recovery.project,P);assert.equal(app.recovery.draft.note,'note draft');assert.equal(data.size,0);await app.logout();assert.equal(app.recovery,null);});
test('same-account explicit draft recovery works; different account discards recovery',async()=>{const {app}=setup(async url=>url.includes('/token')?response({access_token:'token',expires_in:10}):url.endsWith('/user')?response({id:B}):response([]));app.recovery={user:A,project:P,draft:{plan:'private'}};await app.login('B','password');assert.equal(app.recovery,null);});
test('double save is single-flight; successful note appends user content once',async()=>{let release,calls=0;const blocked=new Promise(r=>release=r);const {app}=setup(async()=>{calls++;await blocked;return response([{id:Q,owner_id:A,project_id:P,content:'note draft'}]);});logged(app);const save=app.save('note');await app.save('note');release();await save;assert.equal(calls,1);assert.equal(app.state.notes.length,1);assert.equal(app.state.draft.note,'');});
test('validation rejects unsafe URLs, overflow and query injection',()=>{assert.equal(repoURL(''),'');assert.equal(repoURL('https://github.com/owner/repo'),'https://github.com/owner/repo');for(const u of ['javascript:alert(1)','https://github.com/a/..','https://github.com/a/r?q=x','https://user:pass@github.com/a/r'])assert.throws(()=>repoURL(u));assert.throws(()=>text('x'.repeat(101),1,100,'name'));assert.throws(()=>text(' ',1,100,'name'));assert.throws(()=>projectId(P+'&owner_id=eq.'+B));});
test('network save failure keeps original drafts with no retry',async()=>{let calls=0;const {app}=setup(async()=>{calls++;throw Error('offline');});logged(app);await app.save('note');assert.equal(calls,1);assert.equal(app.state.draft.note,'note draft');assert.equal(app.state.notes.length,0);assert.equal(app.state.busy,false);});
test('expired bound draft is recovered only by explicit same-account/project action',async()=>{const {app}=setup(async url=>url.includes('wb_notes')?response([]):response([{id:P,owner_id:A,plan:'saved',repo_url:''}]));logged(app);app.expire();app.state.user={id:A};app.state.session={token:'new',expiresAt:10000};app.state.view='home';assert.equal(app.state.project,null);await app.restoreDraft();assert.equal(app.state.project.id,P);assert.equal(app.state.draft.plan,'draft');assert.equal(app.state.draft.note,'note draft');assert.equal(app.recovery,null);});
test('new-project draft survives expiry in memory and different login discards it',async()=>{const {app,data}=setup(async()=>response([]));logged(app);app.newProject();app.state.newDraft={name:'private',summary:'idea'};app.expire();assert.equal(data.size,0);assert.equal(app.recovery.view,'new');app.state.user={id:A};app.state.session={token:'new',expiresAt:10000};await app.restoreDraft();assert.equal(app.state.newDraft.summary,'idea');app.newProject();assert.equal(app.state.newDraft.name,'');});
test('incorrect password shows login failure without claiming session expiry',async()=>{const {app,data}=setup(async()=>response({},400));await app.login('bad','bad');assert.match(app.state.error,/無法登入/);assert.equal(data.size,0);assert.equal(app.state.busy,false);});

test('default transport preserves browser fetch receiver instead of invoking it as a Workbench method',async()=>{const previous=globalThis.fetch,calls=[];try{globalThis.fetch=function(url,opts){if(this!==undefined&&this!==globalThis)throw new TypeError('Illegal invocation');calls.push(url);return Promise.resolve(url.includes('/token')?response({access_token:'opaque',expires_in:10}):url.endsWith('/user')?response({id:A}):response([]));};const data=new Map(),storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};const app=new Workbench({url:'https://example.supabase.co',key:'public'},{storage,now:()=>100});await assert.rejects(async()=>({fetcher:globalThis.fetch}).fetcher('probe'),/Illegal invocation/);await app.login('user@example.com','password');assert.equal(app.state.user.id,A);assert.equal(app.state.view,'home');assert.equal(app.state.error,'');assert.equal(calls.length,3);assert.ok(data.has('wb-session'));}finally{globalThis.fetch=previous;}});
