import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, mkdirSync, writeFileSync, symlinkSync, unlinkSync, realpathSync, chmodSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Store } from '../store.mjs';
import { Runtime } from '../runtime.mjs';
import { Projects, command, githubRepo } from '../projects.mjs';
import { createWorkbench } from '../server.mjs';
const here=dirname(fileURLToPath(import.meta.url)),fixture=join(here,'fixture.mjs'),frameworkRoot=resolve(here,'../../..');
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){const end=Date.now()+6000;while(Date.now()<end){if(fn())return;await pause(20);}throw Error('timeout');}
function setup(mode='success'){
 const dir=realpathSync(mkdtempSync(join(tmpdir(),'wb-project-test-'))),store=new Store(join(dir,'data/store.sqlite')),runtime=new Runtime(store,{testCommand:{executable:process.execPath,args:[fixture,mode,join(dir,'heartbeat'),join(dir,'childpid')]}});
 const state={owner:'tester',exists:false,repo:'',description:'',base:'b'.repeat(40),tree:[],creates:0,prs:0,developFail:false,remoteWrites:0};
 const run=async(exe,args,cwd,input)=>{
  if(exe==='git')return command(exe,args,cwd,input);
  if(args[0]==='repo'&&args[1]==='view'){if(!state.exists){const e=Error('not found');e.code=1;throw e;}return JSON.stringify({nameWithOwner:state.repo,isPrivate:true,description:state.description,defaultBranchRef:{name:'main'}});}
  if(args[0]==='repo'&&args[1]==='create'){state.creates++;state.exists=true;state.repo=args[2];state.description=args.at(-1);return '';}
  if(args[0]==='api'){
   const path=args[3],body=input?JSON.parse(input):null;if(body)state.remoteWrites++;
   if(path==='user')return JSON.stringify({login:state.owner});
   if(path.endsWith('/commits/main')||path.endsWith('/commits/HEAD'))return JSON.stringify({sha:state.base,commit:{tree:{sha:'a'.repeat(40)}}});
   if(path.includes('/git/trees/')&&!body)return JSON.stringify({tree:state.tree,truncated:false});
   if(path.endsWith('/git/trees'))return JSON.stringify({sha:'c'.repeat(40)});
   if(path.endsWith('/git/commits'))return JSON.stringify({sha:'d'.repeat(40)});
   if(path.endsWith('/git/refs/heads/main')){state.base=body.sha;return '{}';}
   if(path.endsWith('/git/refs')){if(state.developFail&&body.ref==='refs/heads/develop'){state.developFail=false;const e=Error('temporary');e.code=2;throw e;}return '{}';}
   if(path.endsWith('/pulls')){state.prs++;return JSON.stringify({html_url:'https://github.com/tester/project/pull/'+state.prs});}
  }throw Error('Unexpected mock command '+JSON.stringify(args));
 };
 const projects=new Projects(store,runtime,{root:join(dir,'projects'),frameworkRoot,gh:'fixture-gh',run});
 return {dir,store,runtime,projects,state,async close(){await runtime.shutdown();store.close();rmSync(dir,{recursive:true,force:true});}};
}
const proposal={name:'project',businessGoal:'Goal',primaryUsers:'Owner',coreFeatures:'Chat',primaryPlatform:'Mac',recommendedStack:'Node',openQuestions:'TBD design'};
test('AC008 GitHub validation rejects credentials/options/traversal and draft stays local',async()=>{
 assert.equal(githubRepo('https://github.com/tester/project.git'),'tester/project');for(const url of ['https://user:secret@github.com/a/b','file:///tmp/repo','https://github.com/a/b?x=1','https://github.com/a/../x','--upload-pack=evil','https://github.com/a/b/tree/main'])assert.throws(()=>githubRepo(url));
 const x=setup();try{const a=await x.projects.create({name:'First',summary:'token=private-secret'}),b=await x.projects.create({name:'Second',summary:'other'});assert.notEqual(a.path,b.path);assert.equal(x.state.creates,0);assert.equal(a.repo,'');assert.ok(!a.summary.includes('private-secret'));assert.equal(x.projects.list().length,2);}finally{await x.close();}
});
test('AC009 full proposal, explicit approval, current identity, expiry and replay prevent effects',async()=>{
 const x=setup();try{const p=await x.projects.create({name:'Idea',summary:'Summary'}),a=await x.projects.proposal(p.id,proposal);for(const k of ['businessGoal','primaryUsers','coreFeatures','primaryPlatform','recommendedStack','openQuestions','owner','provider','visibility'])assert.ok(a[k]);assert.equal(x.state.creates,0);x.state.owner='changed';await assert.rejects(x.projects.provision(p.id,a.approval),/身分/);assert.equal(x.state.creates,0);await assert.rejects(x.projects.provision(p.id,a.approval),/失效/);x.state.owner='tester';const expired=await x.projects.proposal(p.id,proposal);x.projects.now=()=>Date.now()+301000;await assert.rejects(x.projects.provision(p.id,expired.approval),/失效/);assert.equal(x.state.creates,0);}finally{await x.close();}
});
test('AC009 partial provisioning retries exact target, no duplicate creation; bootstrap pending/provenance',async()=>{
 const x=setup();try{const p=await x.projects.create({name:'Idea',summary:'Summary'});x.state.developFail=true;const a=await x.projects.proposal(p.id,proposal);await assert.rejects(x.projects.provision(p.id,a.approval));assert.equal(x.projects.get(p.id).provision_state,'PARTIAL');assert.equal(x.state.creates,1);await assert.rejects(x.projects.proposal(p.id,{...proposal,name:'other'}),/原 repo/);const retry=await x.projects.proposal(p.id,proposal);const done=await x.projects.provision(p.id,retry.approval);assert.equal(done.repo,'tester/project');assert.equal(done.provision_state,'LINKED');assert.equal(x.state.creates,1);const provenance=JSON.parse(readFileSync(join(p.path,'framework.json'),'utf8'));assert.equal(provenance.status,'SPEC_REVIEW_PENDING');assert.match(provenance.framework.version,/^[a-f0-9]{40}$/);assert.match(readFileSync(join(p.path,'specs/project/spec.md'),'utf8'),/TBD/);}finally{await x.close();}
});
test('AC009 existing repository name never adopted or altered',async()=>{
 const x=setup();try{const p=await x.projects.create({name:'Idea',summary:''});x.state.exists=true;x.state.repo='tester/project';const a=await x.projects.proposal(p.id,proposal);await assert.rejects(x.projects.provision(p.id,a.approval),/已存在/);assert.equal(x.state.creates,0);assert.equal(x.state.remoteWrites,0);assert.equal(x.projects.get(p.id).repo,'');}finally{await x.close();}
});
test('AC010/011 FIFO model identity, cross-project isolation, queued cancellation and persistence',async()=>{
 const x=setup('hang');try{const a=await x.projects.create({name:'A',summary:'a'}),b=await x.projects.create({name:'B',summary:'b'});const first=x.projects.message(a.id,{text:'only-A',model:'gpt-6-sol'});await until(()=>x.runtime.active);const second=x.projects.message(b.id,{text:'only-B',model:'gpt-6-luna'});assert.equal(x.store.get(second.id).status,'CREATED');assert.equal(x.runtime.queue.length,1);assert.equal(x.store.get(first.id).model,'gpt-6-sol');assert.ok(!x.store.get(second.id).prompt.includes('only-A'));assert.equal(x.store.get(first.id).integrity,true);assert.throws(()=>x.projects.message(a.id,{text:'x',model:'arbitrary'}),/模型/);x.runtime.cancel(second.id);assert.equal(x.store.get(second.id).status,'CANCELLED');assert.equal(x.runtime.queue.length,0);await assert.rejects(x.projects.preview(a.id,{}),/仍有任務/);x.runtime.cancel(first.id);await until(()=>!x.runtime.active);assert.equal(x.projects.view(b.id).messages[0].text,'only-B');}finally{await x.close();}
});
test('AC010 restart preserves projects/conversation and never replays CREATED queued work',async()=>{
 const x=setup();try{const p=await x.projects.create({name:'Persist',summary:''});const t=x.store.create(p.path,'queued','gpt-6-sol');x.store.db.prepare('INSERT INTO messages VALUES(?,?,?,?,?,?,?,?)').run('msg',p.id,'user','Original',t.id,t.model,'',new Date().toISOString());x.store.close();const restored=new Store(x.store.path);const rt=new Runtime(restored);const pr=new Projects(restored,rt,{root:x.projects.root,frameworkRoot,gh:'fixture-gh'});assert.equal(restored.get(t.id).status,'FAILED_RUNTIME');assert.equal(pr.view(p.id).messages[0].text,'Original');assert.equal(rt.queue.length,0);restored.close();}finally{rmSync(x.dir,{recursive:true,force:true});}
});
test('AC012 skill source, instruction-only selection, symlink/script/traversal and size boundaries',async()=>{
 const x=setup();try{const p=await x.projects.create({name:'Skill',summary:''}),base=join(p.path,'.agents/skills/demo');mkdirSync(base,{recursive:true});writeFileSync(join(base,'SKILL.md'),'Use concise answers.');writeFileSync(join(base,'script.sh'),'do-not-run');const skills=x.projects.skills(p.id);assert.equal(skills.length,1);assert.equal(skills[0].platform,'Codex instructions');assert.throws(()=>x.projects.message(p.id,{text:'x',skill:'../../secret'}),/技能/);symlinkSync('/tmp',join(p.path,'.agents/skills/unsafe'));assert.throws(()=>x.projects.skills(p.id),/符號連結/);unlinkSync(join(p.path,'.agents/skills/unsafe'));writeFileSync(join(base,'SKILL.md'),'x'.repeat(32769));assert.throws(()=>x.projects.skills(p.id),/安全範圍/);writeFileSync(join(base,'SKILL.md'),'Use concise answers.');const chosen=x.projects.message(p.id,{text:'hello',skill:skills[0].id});assert.match(x.store.get(chosen.id).prompt,/Use concise answers/);assert.ok(!x.store.get(chosen.id).prompt.includes('do-not-run'));x.runtime.cancel(chosen.id);}finally{await x.close();}
});
test('AC013 explicit exact record preview, chat opt-in, owner paths/remote stale checks and PR-only writes',async()=>{
 const x=setup();try{const p=await x.projects.create({name:'Sync',summary:'Summary'});x.state.exists=true;x.state.repo='tester/project';const row=x.projects.get(p.id);row.repo=x.state.repo;row.provision_state='LINKED';x.projects.save(row);const a=await x.projects.preview(p.id,{});assert.deepEqual(Object.keys(a.files),['workbench/PROJECT.md','workbench/DECISIONS.md']);assert.equal(x.state.prs,0);assert.equal(x.state.remoteWrites,0);x.state.base='e'.repeat(40);await assert.rejects(x.projects.sync(p.id,a.approval),/遠端已更新/);assert.equal(x.state.remoteWrites,0);const b=await x.projects.preview(p.id,{includeChat:true});assert.ok(b.files['workbench/CHAT.md']);const result=await x.projects.sync(p.id,b.approval);assert.match(result.branch,/^workbench\//);assert.equal(x.state.prs,1);assert.equal(x.projects.view(p.id).lastPR.url,result.url);await assert.rejects(x.projects.sync(p.id,b.approval),/失效/);x.state.tree=[{path:'workbench',mode:'120000',type:'blob',sha:'bad'}];await assert.rejects(x.projects.preview(p.id,{}),/符號連結/);}finally{await x.close();}
});
test('AC011 production CLI command receives selected model without shell substitution',async()=>{
 const x=setup();try{const p=await x.projects.create({name:'Model',summary:''}),capture=join(x.dir,'args.json'),exe=join(x.dir,'codex-fixture');writeFileSync(exe,'#!'+process.execPath+'\nimport{writeFileSync}from"node:fs";writeFileSync('+JSON.stringify(capture)+',JSON.stringify(process.argv.slice(2)));process.stdin.resume();process.stdin.on("end",()=>{for(const e of [{type:"turn.started"},{type:"item.completed",item:{type:"agent_message",text:"verified"}},{type:"turn.completed"}])console.log(JSON.stringify(e));});\n');chmodSync(exe,0o700);x.runtime.testCommand=null;x.runtime.executable=exe;const t=x.projects.message(p.id,{text:'model identity',model:'gpt-6-astra'});await until(()=>x.store.get(t.id).status==='COMPLETED'||x.store.get(t.id).status==='FAILED_RUNTIME');assert.equal(x.store.get(t.id).status,'COMPLETED');const args=JSON.parse(readFileSync(capture,'utf8'));assert.equal(args[args.indexOf('-m')+1],'gpt-6-astra');assert.ok(args.includes('--ignore-user-config'));assert.ok(args.includes('read-only'));}finally{await x.close();}
});
test('AC008/010 project HTTP isolation/input allowlist/CSRF and no repo side effect from chat',async()=>{
 const x=setup();x.store.close();const app=await createWorkbench({dataPath:join(x.dir,'data/store.sqlite'),port:0,runtimeReady:{ready:true},runtimeOptions:{testCommand:{executable:process.execPath,args:[fixture,'success']}},projectsOptions:{gh:'fixture-gh',run:x.projects.run}});try{const b=await(await fetch(app.origin+'/api/bootstrap')).json();const headers={'Content-Type':'application/json',Origin:app.origin,'X-Workbench-Token':b.csrf};const post=async(path,body)=>fetch(app.origin+path,{method:'POST',headers,body:JSON.stringify(body)});assert.equal((await post('/api/projects',{name:'P',summary:'x',executable:'evil'})).status,400);const p=await(await post('/api/projects',{name:'P',summary:'x'})).json();assert.equal((await fetch(app.origin+'/api/projects/'+p.id+'/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,403);const t=await(await post('/api/projects/'+p.id+'/messages',{text:'hello',model:'gpt-6-sol'})).json();await until(()=>app.store.get(t.id).status==='COMPLETED');const v=await(await fetch(app.origin+'/api/projects/'+p.id)).json();assert.equal(v.messages.length,2);assert.equal(v.messages[1].role,'assistant');assert.equal(x.state.creates,0);}finally{await app.close();rmSync(x.dir,{recursive:true,force:true});}
});

test('AC010 queue maximum and true FIFO across projects; no process overlap',async()=>{
 const x=setup();try{const a=await x.projects.create({name:'FIFO-A',summary:''}),b=await x.projects.create({name:'FIFO-B',summary:''});const order=[];const launch=x.runtime.launch.bind(x.runtime);let live=0,max=0;x.runtime.launch=async(job,prompt)=>{order.push(job.id);live++;max=Math.max(max,live);try{await launch(job,prompt);}finally{live--;}};const ids=[];for(let i=0;i<20;i++)ids.push(x.projects.message(i%2?a.id:b.id,{text:'queued '+i}).id);assert.throws(()=>x.projects.message(a.id,{text:'overflow'}),/20/);assert.equal(x.store.list().length,20);await until(()=>order.length===20&&!x.runtime.active);assert.deepEqual(order,ids);assert.equal(max,1);assert.ok(ids.every(id=>x.store.get(id).status==='COMPLETED'));}finally{await x.close();}
});

test('AC005/010 failed conversation persistence prevents queued spawn and further dispatch',async()=>{
 const x=setup();try{const p=await x.projects.create({name:'Storage',summary:''});x.store.db.exec("CREATE TRIGGER fail_message BEFORE INSERT ON messages BEGIN SELECT RAISE(ABORT,'injected'); END;");assert.throws(()=>x.projects.message(p.id,{text:'must not run'}));assert.match(x.runtime.fatal,/儲存失敗/);await pause(50);assert.equal(x.runtime.active,null);assert.equal(x.runtime.queue.length,0);assert.equal(x.store.list()[0].status,'CANCELLED');assert.throws(()=>x.projects.message(p.id,{text:'later'}),/儲存服務失敗/);}finally{await x.close();}
});

test('AC010 legacy HTTP task and managed writes share canonical project guard in both directions',async()=>{
 const x=setup();x.store.close();const managedAlias=join(x.dir,'managed-root-alias');symlinkSync(x.projects.root,managedAlias);const app=await createWorkbench({dataPath:join(x.dir,'data/store.sqlite'),port:0,runtimeReady:{ready:true},runtimeOptions:{testCommand:{executable:process.execPath,args:[fixture,'hang']}},projectsOptions:{root:managedAlias,gh:'fixture-gh',run:x.projects.run}});try{
 const b=await(await fetch(app.origin+'/api/bootstrap')).json(),headers={'Content-Type':'application/json',Origin:app.origin,'X-Workbench-Token':b.csrf};const post=(path,body)=>fetch(app.origin+path,{method:'POST',headers,body:JSON.stringify(body)});const p=await(await post('/api/projects',{name:'Legacy',summary:''})).json();const other=await(await post('/api/projects',{name:'Other',summary:''})).json();
 const started=await post('/api/tasks',{project:join(managedAlias,p.id),prompt:'legacy'});assert.equal(started.status,202);const task=await started.json();assert.equal(app.store.db.prepare('SELECT COUNT(*) AS n FROM messages WHERE task_id=?').get(task.id).n,0);assert.equal(app.projects.busy(p.id),true);assert.equal(app.projects.busy(other.id),false);for(const route of ['preview','provision','sync']){const response=await post('/api/projects/'+p.id+'/'+route,route==='preview'?{}:{approval:'invalid'});assert.equal(response.status,400);assert.match((await response.json()).error,/仍有任務/);}assert.equal(x.state.remoteWrites,0);app.runtime.cancel(task.id);await until(()=>!app.runtime.active);assert.equal(app.projects.busy(p.id),false);
 let release;const blocked=new Promise(resolve=>release=resolve);const lock=app.projects.exclusive(p.id,()=>blocked);const alias=join(x.dir,'alias');symlinkSync(p.path,alias);const denied=await post('/api/tasks',{project:alias,prompt:'reverse'});assert.equal(denied.status,409);assert.equal(app.runtime.active,null);release();await lock;const allowed=await post('/api/tasks',{project:alias,prompt:'after unlock'});assert.equal(allowed.status,202);app.runtime.cancel((await allowed.json()).id);assert.equal(x.state.remoteWrites,0);
 }finally{await app.close();rmSync(x.dir,{recursive:true,force:true});}
});

test('AC015 aliased managed root and legacy row identities preserve immutable task evidence',async()=>{
 const x=setup('hang');try{const alias=join(x.dir,'managed-alias');symlinkSync(x.projects.root,alias);const pr=new Projects(x.store,x.runtime,{root:alias,frameworkRoot,gh:'fixture-gh',run:x.projects.run});assert.equal(pr.root,x.projects.root);const p=await pr.create({name:'Alias',summary:'idea'}),other=await pr.create({name:'Other',summary:'other'}),oldPath=join(alias,p.id);x.store.db.prepare('UPDATE projects SET path=? WHERE id=?').run(oldPath,p.id);const legacy=x.store.create(oldPath,'historical legacy','gpt-6-luna'),before=JSON.stringify(x.store.get(legacy.id));const restored=new Projects(x.store,x.runtime,{root:alias,frameworkRoot,gh:'fixture-gh',run:x.projects.run});assert.equal(restored.get(p.id).path,p.path);assert.equal(restored.busy(p.id),true);assert.equal(restored.busy(other.id),false);assert.equal(JSON.stringify(x.store.get(legacy.id)),before);await assert.rejects(restored.exclusive(p.id,async()=>{}),/仍有任務/);x.runtime.cancel(legacy.id);restored.locks.add(p.id);assert.throws(()=>restored.guardLegacyPath(oldPath),e=>e.statusCode===409);restored.locks.delete(p.id);restored.guardLegacyPath(oldPath);assert.equal(x.state.remoteWrites,0);}finally{await x.close();}
});
